apiVersion: v1
kind: Service
metadata:
  name: {{service}}-node-srv
spec:
  type: NodePort
  selector:
    app: {{service}}
  ports:
    - name: {{service}}
      protocol: TCP
      port: {{port}}
      targetPort: {{port}}

